version: "3.9"

services:
  app:
    image: aifrak/real-time-phoenix:latest
    build:
      context: .
      target: base
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    command: sleep infinity
    ports:
      - 4000:4000
    volumes:
      - .:/app
